### ISSUE TITLE
error:0308010C:digital envelope routines::unsupported while running npm run dev

### ISSUE THREAD

**Issue by Chetan-KK** [brunosimon/folio-2019#37]
> three.js-template@1.0.0 dev
> webpack-dev-server --config ./bundler/webpack.dev.js

i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from ./dist
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\Clones\folio-2019\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\Clones\folio-2019\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\Clones\folio-2019\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\Clones\folio-2019\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\Clones\folio-2019\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\Clones\folio-2019\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\Clones\folio-2019\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (D:\Clones\folio-2019\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\Clones\folio-2019\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\Clones\folio-2019\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at D:\Clones\folio-2019\node_modules\graceful-fs\graceful-fs.js:115:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by mehranshoghii** [comment]
same here
