### ISSUE TITLE
npm run dev This appears

### ISSUE THREAD

**Issue by NOeSIS-yu** [brunosimon/folio-2019#38]
$ npm run dev

> three.js-template@1.0.0 dev
> webpack-dev-server --config ./bundler/webpack.dev.js

D:\github\folio-2019\node_modules\webpack-cli\bin\convert-argv.js:7
const validateSchema = process.webpackModule.validateSchema;
                                             ^

TypeError: Cannot read properties of undefined (reading 'validateSchema')
    at Object.<anonymous> (D:\github\folio-2019\node_modules\webpack-cli\bin\convert-argv.js:7:46)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\github\folio-2019\node_modules\webpack-dev-server\bin\webpack-dev-server.js:234:15)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)

Node.js v18.16.0

**Comment by RawHit02** [comment]
@NOeSIS-yu do one thing clone this and then use terminal in the GUT Lens it get directly changed there or you can also create a new project via npm commands and then try to remove some files and paste this code files
