### ISSUE TITLE
issue raised when `npm run dev`

### ISSUE THREAD

**Issue by Mqgh2013** [brunosimon/folio-2019#41]
folio-2019-master npm run dev

> three.js-template@1.0.0 dev
> webpack-dev-server --config ./bundler/webpack.dev.js

/Users/rzhang1/Downloads/folio-2019-master/node_modules/copy-webpack-plugin/node_modules/schema-utils/dist/validate.js:158
    throw new _ValidationError.default(errors, schema, configuration);
    ^

ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options[0] has an unknown property 'from'. These properties are valid:
   object { patterns, options? }
    at validate (/Users/rzhang1/Downloads/folio-2019-master/node_modules/copy-webpack-plugin/node_modules/schema-utils/dist/validate.js:158:11)
    at new CopyPlugin (/Users/rzhang1/Downloads/folio-2019-master/node_modules/copy-webpack-plugin/dist/index.js:172:5)
    at Object.<anonymous> (/Users/rzhang1/Downloads/folio-2019-master/bundler/webpack.common.js:15:9)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/Users/rzhang1/Downloads/folio-2019-master/bundler/webpack.dev.js:2:29) {
  errors: [
    {
      instancePath: '[0]',
      schemaPath: '#/additionalProperties',
      keyword: 'additionalProperties',
      params: { additionalProperty: 'from' },
      message: 'must NOT have additional properties',
      schema: false,
      parentSchema: {
        definitions: {
          ObjectPattern: {

**Comment by Mqgh2013** [comment]
node version 16.20

**Comment by Mqgh2013** [comment]
no worries, looks like fix it through here https://stackoverflow.com/questions/61937054/npm-run-dev-fails-validationerror-invalid-options-object
